id: b0bcf2fb39864d498d144b38af116cd5
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_285-The_Dedication_Fulfilling_All_Aspirations-v2
  language: en
  author: ''
  volume: {}
